use clap::{App, Arg};
use clap::crate_version;

pub struct CliApp;

impl CliApp {
    pub fn create_cli_app(&self) -> App {
        let app = App::new("chopper")
            .version(crate_version!())
            .about("chopper is a simple streaming time series tool")
            .arg(Arg::with_name("input")
                .help("sets the input files to use; \nif missing, stdin will be used")
                .multiple(true))
            .arg(Arg::with_name("output")
                .long("output")
                .short("o")
                .help("output to a file")
                .takes_value(true)
                .value_name("FILE"))
            .arg(Arg::with_name("timezone")
                .long("timezone")
                .help("specify time zone for timestamp.")
                .takes_value(true)
                .case_insensitive(true)
                .value_name("ARG"))
            .arg(Arg::with_name("begin")
                .short("b")
                .long("begin")
                .help("set begin timestamp (inclusive); \ndate: yyyymmdd, time: hh:mm:ss")
                .takes_value(true)
                .value_name("TIMESTAMP"))
            .arg(Arg::with_name("end")
                .short("e")
                .long("end")
                .help("set end timestamp (exclusive); \ndate: yyyymmdd, time: hh:mm:ss")
                .takes_value(true)
                .value_name("TIMESTAMP"))
            .arg(Arg::with_name("backtrace")
                .long("backtrace")
                .help("print backtrace"))
            //  below are csv only
            .arg(Arg::with_name("csv_input_delimiter")
                .long("csv-in-delimiter")
                .help("csv only: input field/column delimiter")
                .takes_value(true)
                .default_value(",")
                .value_name("ARG"))
            .arg(Arg::with_name("csv_output_delimiter")
                .long("csv-out-delimiter")
                .help("csv only: output field/column delimiter")
                .takes_value(true)
                .default_value(",")
                .value_name("ARG"))
            .arg(Arg::with_name("csv_has_header")
                .long("csv-has-header")
                .help("csv only: input files have header"))
            .arg(Arg::with_name("csv_print_timestamp")
                .long("csv-print-timestamp")
                .help("csv only: print timestamp as first column")
                .takes_value(true)
                .default_value("auto")
                .possible_values(&["true", "false", "auto"])
                .case_insensitive(true)
                .value_name("ARG"))
            .arg(Arg::with_name("csv_timestamp_col_date")
                .long("csv-timestamp-date")
                .help("csv only: specify the timestamp date column index")
                .takes_value(true)
                .default_value("0")
                .value_name("ARG"))
            .arg(Arg::with_name("csv_timestamp_col_time")
                .long("csv-timestamp-time")
                .help("csv only: specify the timestamp time column index")
                .takes_value(true)
                .value_name("ARG"))
            .arg(Arg::with_name("csv_timestamp_format_date")
                .long("csv-timestamp-fmt-date")
                .help("csv only: specify the timestamp date format [default: %Y%m%d]")
                .takes_value(true)
                .value_name("ARG")
                .requires("timezone"))
            .arg(Arg::with_name("csv_timestamp_format_time")
                .long("csv-timestamp-fmt-time")
                .help("csv only: specify the timestamp time format [default: %H:%M:%S]")
                .takes_value(true)
                .value_name("ARG")
                .requires_all(&["csv_timestamp_format_date", "timezone"]));
        app
    }
}
